# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Add Zig
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.local/bin/zig-linux-x86_64-0.12.0-dev.3161+377ecc6af" >> $HOME/.bashrc
      mkdir -p ~/.local/bin/zig
      curl -o ./zig.tar.xz https://ziglang.org/builds/zig-linux-x86_64-0.12.0-dev.3161+377ecc6af.tar.xz && tar -xf zig.tar.xz -C ~/.local/bin
      rm zig.tar.xz
      source $HOME/.bashrc
      
# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
